recipe: default.v1

assistant_id: Vita_Kids_Asistente

language: es

pipeline:
  - name: WhitespaceTokenizer
    intent_tokenization_flag: false
    token_pattern: None

  - name: RegexFeaturizer

  - name: LexicalSyntacticFeaturizer

  - name: CountVectorsFeaturizer
    OOV_token: "__oov__"
    min_ngram: 1
    max_ngram: 2

  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4

  - name: DIETClassifier
    epochs: 150
    constrain_similarities: true
    entity_recognition: true
    learning_rate: 0.005
    BILOU_flag: true

  - name: RegexEntityExtractor
    case_sensitive: false

  - name: EntitySynonymMapper

  - name: ResponseSelector
    epochs: 100
    retrieval_intent: None


policies:
  - name: MemoizationPolicy
    max_history: 5

  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True

  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100

  - name: TEDPolicy
    max_history: 5
    epochs: 150
    batch_size: [32, 64]
    constrain_similarities: true
